### ISSUE TITLE
Doesn't build with recent versions

### ISSUE THREAD

**Issue by thenewwazoo** [mathetake/proxy-wasm-rust-nullvm#1]
Hi! Thanks so much for your work on this. I've spent the last few days trying to bring this up-to-date (with Envoy 1.30.2, specifically) as an experiment for writing pure-Rust filters, as some internal benchmarks showed the CPU and memory requirements of using WASM to be too much.

I've gotten pretty close, updating a number of dependencies, the C++ glue to match some missing functions, and so on. I'm currently working through issues at the interface between `Envoy::Extensions::Common::Wasm` and `proxy_wasm` having (I suspect) to do with thread-local storage quirks.

My questions, I suppose are:
* Without trying to litigate the suitability and performance of WASM, what are your thoughts about using your work here as a basis for pure-Rust filters?
* If I submit a PR (which I'd love to do), would you be willing to accept and provide feedback on it?

**Comment by mathetake** [comment]
are you in Envoy community slack? ping me on the DM there - I have some info to share on these questions

**Comment by thenewwazoo** [comment]
Discussed via Slack, so I'll close this issue.
